### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by ialexca** [yolo-hipster/yolo-hipster#13]
Description:
Définir chaque cas d'utilisations de l'API Yolo-Hipsters en se basant sur le Wiki de Anne, section Collaborations.

Complétion:
Faire un document contenant chaque cas d'utilisation du Web App. Le web app devra répondre aux demande du Wiki de Anne, section collaboration.

Dépendance:
Aucune

**Comment by sophiedeziel** [comment]
Il y a une page du wiki qui est prète pour ça
https://github.com/yolo-hipster/yolo-hipster/wiki/Use-Cases

**Comment by ialexca** [comment]
Les uses cases principaux sont fait. Il est certain que le document restera vivant tout au cours du projet.

Le document produit répond au definition of done de ce issue.
