### ISSUE TITLE
Faire le backlog du sprint 1

### ISSUE THREAD

**Issue by sophiedeziel** [yolo-hipster/yolo-hipster#2]

**Comment by ialexca** [comment]
J'ai transcrit tous les éléments "Issues" dans le fichier et tous les éléments du fichier dans "Issue".
Le document a été téléverser dans les "Downloads" de GitHub.

**Comment by ialexca** [comment]
Attention, j'ai ajouter traduire le code de l'algorithme de catégorisation des éditions de collaboration au fichier du backlog.
