### ISSUE TITLE
Coder et raffiner la collecte de Data

### ISSUE THREAD

**Issue by ialexca** [yolo-hipster/yolo-hipster#34]

**Comment by prega** [comment]
Décodage des JSONs un peu plus problématique que prévu.
Construction de quelques fonctions pour résoudre le cas.
Des nouvelles en soirée ou dimanche.

**Comment by ialexca** [comment]
Utilises-tu une librairie JSON? Si oui laquel, si non, je te suggère http://code.google.com/p/google-gson/

**Comment by prega** [comment]
Merci, mais c'est bon en fin de compte!

**Comment by prega** [comment]
Des ajouts seront fait avec le temps et nécessités.
