### ISSUE TITLE
Configurer Git en local - rlamour

### ISSUE THREAD

**Issue by sophiedeziel** [yolo-hipster/yolo-hipster#8]

**Comment by rlamour** [comment]
???? Quoi? What? Why?

**Comment by sophiedeziel** [comment]
J'aurais du être plus précise...

Fais juste t'assurer que tu peux push et pull de ton ordi...

**Comment by rlamour** [comment]
Ok, thanks

**Comment by rlamour** [comment]
Bonjour Sophie, as-tu le email du prof?
