### ISSUE TITLE
Réussir à fetcher des infos de l'API de MediaWiki grâce à PHP

### ISSUE THREAD

**Issue by sophiedeziel** [yolo-hipster/yolo-hipster#9]

**Comment by prega** [comment]
-Tests de divers requêtes- 
-Obtenir les utilisateurs qui ont fait une révision
-Obtenir les révisions d'un utilisateur spécifique 
-Obtenir le contenu des révisions
-Obtenir les id de tous les révisions
-Obtenir les noms des sections

**Comment by ialexca** [comment]
Les noms de section sont dans le texte. Par exemple, il faut trouver tous les ==Section1==, ===Section1.1===, ==Section2== dans le texte. L'algorithme fera la job pour toi...
